export interface MenuGroup {
  heading?: string;
  items: string[];
}

export interface CateringMenuSection {
  id: string;
  title: string;
  groups: MenuGroup[];
}

export const cateringMenu: CateringMenuSection[] = [
  {
    id: 'menu-brunch',
    title: 'Brunch / Breakfast',
    groups: [
      {
        items: [
          'Sausage (Deer meat, Turkey, Beef, Alligator, or Pork)',
          'Bacon (Pork or Turkey)',
          'French Toast',
          'Crepes',
          'Pancakes',
          'Waffles',
          'Biscuits',
          'Breakfast eggs',
          'Omelettes',
          'Muffins of your Choice',
          'Oatmeal',
          'Fruit Bowl',
          'Avocado With Veggies (Eggs optional)',
          'Shrimp and Grits',
          'Oxtails and Grits',
          'Catfish and Grits',
          'Cinnamon Rolls',
          'Butter Croissant',
          'Chocolate Croissant',
          'Pain au Raisin',
          'Fruit Parfait (Granola or Oreo Cookies)',
          'Breakfast Potatoes',
          'Fried Chicken (legs or wings)',
        ],
      },
      {
        heading: 'Brunch / Breakfast Drinks',
        items: [
          'Hibiscus Tea',
          'Pineapple Ginger Juice',
          'Pineapple Juice',
          'Orange Juice',
          'Apple Juice',
          'Watermelon Juice',
          'Mango Mandarins & Pineapple Juice',
          'Mimosa',
          'Chocolate Milk',
          'Coffee',
          'Green Tea',
          'Mint Tea',
          'Black Tea',
          'Blackberry Tea',
        ],
      },
    ],
  },
  {
    id: 'menu-appetizer',
    title: 'Appetizers',
    groups: [
      {
        items: [
          'Oeuf Mimosa / Heaven eggs',
          'Shrimp Cocktails',
          'Grilled Chicken Salad',
          'Seafood Soup with Ginger',
          'Shrimp on the Stick',
          'Veggies Salad',
          'Caesar Salad',
          'House Salad',
          'Potato Salad',
          'Avocado Toast with Soft Boiled Egg & Spring Veggies',
          'Seared Shrimp Stuffed Avocado',
          'Lobster Bisque',
          'Shrimp and Crab Bisque',
          'Coconut Shrimp',
          'Shrimp Tempura',
          'Jumbo Crab & Spinach Dip',
          'Creamy Seafood Soup',
          'Crab Cake',
          'Shrimp Avocado Boats',
          'Grilled Lump Crabmeat & Lobster Stuffed Oysters',
          'Mussels and shrimp cooked in marinara style sauce',
          'Baked Mussels with Cheese',
          'Creamy Garlic Butter Mussels',
          'Leeks and Sweet Potatoes Soup',
          'Squash Soup',
          'Salmon Bites',
          'Tacos (Beef / Chicken / Shrimp)',
        ],
      },
    ],
  },
  {
    id: 'menu-meats',
    title: 'Entrees Meat & Poultry',
    groups: [
      {
        items: [
          'Grilled Garlic & Herb Lamb Chops',
          'Honey Glazed Lamb Chops',
          'Slow Braised Rosemary Lamb Shank',
          'Grilled Garlic & Herb Ribeye',
          'Filet Mignon',
          'Baked / Fried / Roasted Chicken',
          'Creamy Garlic Parmesan Sauce Chicken',
          'Chicken Kabobs',
          'Roasted Beef Ribs',
          'Poulet à la Moutarde (Chicken with Mustard Sauce)',
          'Jerk Chicken (Wings / Legs & Thighs / Whole Chicken)',
          'New York Strip',
          'Curry Goat',
          'Jamaican Style Oxtails',
          'Meatballs in Tomato Sauce',
          'Braised Beef Rigatoni',
          'Chicken Cordon Bleu',
          'Garlic Butter Steak Bites',
          'Juicy Bourbon Butter Ribeye Bites',
          'Braised Beef Short Ribs',
          'Korean Style Beef BBQ Riblets',
          'Glazed Roasted Duck with Orange Sauce',
          'Duck Confit',
          'Smothered Turkey Wings / Legs',
          'Souris d’agneau rôties au miel, citron et thym',
          'Chef DJ’s Burger',
          'Lapin au vin (Rabbit in Wine Sauce)',
        ],
      },
    ],
  },
  {
    id: 'menu-seafood',
    title: 'Entrees Seafood',
    groups: [
      {
        items: [
          'Grilled Lobster Tails',
          'Fried Red Snapper',
          'Seafood Boil',
          'Baked / Fried Catfish Fillet',
          'Creamy Salmon and Scallops with Mushrooms and Spinach',
          'Steamed Fish (Tilapia, Catfish, or Red Snapper)',
          'Cajun Butter Sauté Shrimp',
          'Creamy Garlic Butter Lobster Tails',
          'Creamy Garlic Butter Scallops',
          'Honey Mustard Salmon with Golden Butter',
          'Creamy Herb Salmon and Shrimp',
          'Creamy Tuscan Shrimp',
          'Herb and Butter Cod',
          'Baked Lemon Garlic Cod',
          'Mediterranean Style Cod in Tomato Basil Sauce',
          'Beurre Blanc with Scallops',
          'Butter Poached Lobster Tails',
          'Roasted Branzino',
          'Branzino all’Acqua Pazza (Italian)',
          'Jamaican Style Steamed Red Snapper',
          'Garlic Butter Lobster and Scallops',
        ],
      },
    ],
  },
  {
    id: 'menu-african',
    title: 'African Dishes',
    groups: [
      {
        items: [
          'Peanut Butter soup',
          'Sauce Graine (Palm nuts soup)',
          'Braised whole fish with attiéké (Tilapia / Catfish / Red snapper)',
          'Liberian Sweet potato green sauce',
          'Fried Plantain',
          'Ghana kelewele',
          'Thieboudienne (Senegalese Jollof Rice)',
          'Riz au gras (Burkinabé Jollof Rice)',
          'Sauce Yassa (Senegalese Glazed onions sauce)',
        ],
      },
    ],
  },
  {
    id: 'menu-sides',
    title: 'Sides',
    groups: [
      {
        items: [
          'White Rice',
          'Chef DJ’s Fried Rice',
          'Mac and Cheese',
          'Seafood Loaded Mac & Cheese',
          'Alfredo Pasta',
          'Potatoes au Gratin',
          'Potato Purée',
          'Mashed Potatoes',
          'French Fries',
          'Corn on the Cob / off the Cob',
          'Stir Fried Seafood Noodles',
          'Potatoes and Green Beans Porridge',
          'Mediterranean Herb Roasted Veggies',
          'Jamaican Rice and Peas',
          'Rasta Pasta',
          'Sauté Carrot and Cabbage',
          'Roasted Glazed Carrots',
          'Roasted Crispy Potatoes',
          'Sauté or Steamed Asparagus',
          'Cheesy Tomato Pasta',
          'Collard Greens with Smoked Turkey',
          'Stir Fried Bok Choy with Mushrooms',
          'Drunken Noodles',
        ],
      },
    ],
  },
  {
    id: 'menu-bread',
    title: 'Bread',
    groups: [
      {
        items: [
          'Corn Bread',
          'French Baguette',
          'Dinner Rolls',
          'Toast Garlic Bread',
        ],
      },
    ],
  },
  {
    id: 'menu-desserts',
    title: 'Desserts',
    groups: [
      {
        items: [
          'Cake Marbré',
          'Banane Flambée / Banana Foster',
          'Brownies',
          'Crème Brûlée',
          'Madeleines',
          'African Donuts / Puff Puff',
          'Macarons',
          'Lemon Tart',
          'Fruit Tart',
          'Chocolat Parfait',
          'Fruit Parfait',
          'Fruit Salad with Passion Fruit Cream',
          'Crêpes with Different Flavors',
          'Pistachio & Ricotta Cake',
          'Chocolate Fudge',
          'Chocolate Mousse',
          'Chocolate Temptation',
          'Dubai Chocolate Cake',
          'Carrot Cake',
          'Cheesecake',
          'Caramel Fudge Cheesecake',
          'Strawberry Cheesecake',
          'Nutella Cheesecake',
          'Tres Leches Cake',
          'Lemon Bar',
          'Limoncello Mascarpone',
          'Red Velvet Cake',
        ],
      },
    ],
  },
  {
    id: 'menu-drinks',
    title: 'Drinks & Mocktails',
    groups: [
      {
        items: [
          'Hibiscus Drink',
          'Pineapple Ginger Juice',
          'Sunrise Mocktail (orange, pineapple)',
          'Strawberry Virgin Mojito (strawberry, grenadine syrup, sprite, lime, and mint)',
          'Mocktail Passion / Raspberry',
          'Passion Fruit Mojito',
          'Peach Iced Tea Mocktail',
          'Lychee Rose Cooler',
        ],
      },
    ],
  },
];
